"""Mirror the two display typefaces locally, with pinned hashes.

The console and the partner client are designed around a light-weight serif (Newsreader) and a
monospace with wide tracking (IBM Plex Mono). Linking Google Fonts at run time would break the
offline guarantee the rest of the frontend keeps, so this tool mirrors the woff2 files into
`static/vendor/fonts/` and records a SHA-256 for each. The manifest is committed; the binaries
are not — the same arrangement as `fetch_offline_assets.py`.

  uv run python fetch_fonts.py fetch     # download + pin + emit fonts.css (needs network, once)
  uv run python fetch_fonts.py verify    # re-hash local files against the manifest
  uv run python fetch_fonts.py status    # are the faces present, or is the UI on fallbacks?

`fetch` writes `static/vendor/fonts/fonts.css` with the faces embedded as data: URIs, and splices
the same block into `static/dashboard.html` between its FONTS markers. The dashboard needs the
embedded form because the coordinator serves it as a single bare file with no static mount, so it
cannot fetch a sibling asset. Without this step both surfaces fall back to Georgia and Consolas
and simply look plainer; nothing breaks.

CJK is deliberately not mirrored. A full Noto Serif SC is tens of megabytes, and Songti SC /
SimSun / Microsoft YaHei are already present on the machines this demo runs on.

Whether to redistribute these files is a licensing decision for the project owner. Both families
are SIL Open Font License 1.1, which permits bundling; keep the licence text alongside any
redistribution.
"""
import argparse
import base64
import hashlib
import json
import os
import re
import urllib.error
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.path.join(HERE, "static", "vendor", "fonts")
MANIFEST_PATH = os.path.join(FONT_DIR, "manifest.json")
CSS_PATH = os.path.join(FONT_DIR, "fonts.css")
DASHBOARD_PATH = os.path.join(HERE, "static", "dashboard.html")
MANIFEST_FORMAT = "gba-df-offline-fonts"
MANIFEST_VERSION = 1

BEGIN = "/* ==== FONTS: generated by fetch_fonts.py — do not edit by hand ==== */"
END = "/* ==== /FONTS ==== */"

# A modern UA is what makes Google Fonts serve woff2 rather than ttf; the latin subset of each
# face is a few tens of kilobytes, which is what keeps the embedded form reasonable.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

# Mirrored for the client, but only these are embedded into the tracked dashboard: the display
# serif is only ever set at 300, and the italic is not used at all.
EMBED = {"newsreader-300.woff2", "ibm-plex-mono-400.woff2",
         "ibm-plex-mono-500.woff2", "ibm-plex-mono-600.woff2"}

# (family, style, weight, css query)
FACES = [
    ("Newsreader", "normal", 300, "Newsreader:ital,opsz,wght@0,6..72,300"),
    ("Newsreader", "normal", 400, "Newsreader:ital,opsz,wght@0,6..72,400"),
    ("Newsreader", "italic", 400, "Newsreader:ital,opsz,wght@1,6..72,400"),
    ("IBM Plex Mono", "normal", 400, "IBM+Plex+Mono:wght@400"),
    ("IBM Plex Mono", "normal", 500, "IBM+Plex+Mono:wght@500"),
    ("IBM Plex Mono", "normal", 600, "IBM+Plex+Mono:wght@600"),
]


def _get(url, accept_css=False):
    headers = {"User-Agent": UA}
    if accept_css:
        headers["Accept"] = "text/css,*/*;q=0.1"
    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def _slug(family, style, weight):
    return f"{family.lower().replace(' ', '-')}-{weight}{'-italic' if style == 'italic' else ''}.woff2"


def _latin_src(css_text):
    """Google returns one @font-face per unicode subset; take the plain latin one."""
    blocks = css_text.split("@font-face")
    for block in blocks:
        if "unicode-range" in block and "U+0000-00FF" not in block:
            continue
        match = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if match:
            return match.group(1)
    match = re.search(r"url\((https://[^)]+\.woff2)\)", css_text)
    return match.group(1) if match else None


def fetch():
    os.makedirs(FONT_DIR, exist_ok=True)
    pinned = {}
    existing = _load_manifest()
    for family, style, weight, query in FACES:
        name = _slug(family, style, weight)
        css = _get(f"https://fonts.googleapis.com/css2?family={query}&display=swap",
                   accept_css=True).decode("utf-8")
        url = _latin_src(css)
        if not url:
            raise SystemExit(f"no woff2 in the stylesheet for {family} {weight} {style}")
        blob = _get(url)
        digest = hashlib.sha256(blob).hexdigest()
        prior = (existing.get("files") or {}).get(name)
        if prior and prior["sha256"] != digest:
            raise SystemExit(
                f"{name} does not match the pinned hash.\n"
                f"  pinned {prior['sha256']}\n  got    {digest}\n"
                "Delete the manifest to deliberately re-pin, and review the change.")
        with open(os.path.join(FONT_DIR, name), "wb") as handle:
            handle.write(blob)
        pinned[name] = {"bytes": len(blob), "sha256": digest, "source": url,
                        "family": family, "style": style, "weight": weight}
        print(f"  {name:38s} {len(blob):>7,} bytes")

    with open(MANIFEST_PATH, "w", encoding="utf-8") as handle:
        json.dump({"format": MANIFEST_FORMAT, "version": MANIFEST_VERSION, "files": pinned},
                  handle, indent=2, sort_keys=True)
    with open(CSS_PATH, "w", encoding="utf-8", newline="") as handle:
        handle.write(_render_linked_css(pinned))
    total = sum(f["bytes"] for f in pinned.values())
    print(f"\npinned {len(pinned)} faces, {total:,} bytes -> {MANIFEST_PATH}")
    embedded = _render_embedded_css(pinned)
    _splice_dashboard(embedded)
    print(f"embedded {len(EMBED)} faces ({len(embedded):,} chars) into static/dashboard.html")
    print("the client links static/vendor/fonts/fonts.css and pays no base64 cost")


def _face(meta, src):
    return (f"@font-face{{font-family:'{meta['family']}';font-style:{meta['style']};"
            f"font-weight:{meta['weight']};font-display:swap;"
            f"src:url({src}) format('woff2')}}")


def _render_linked_css(pinned):
    """For the client, which can read sibling files — plain relative URLs, a few hundred bytes."""
    lines = ["/* generated by fetch_fonts.py — do not edit by hand */"]
    lines += [_face(pinned[name], name) for name in sorted(pinned)]
    return "\n".join(lines) + "\n"


def _render_embedded_css(pinned):
    """For the dashboard, which the coordinator serves as one bare file with no static mount.

    Only the faces the design actually uses are embedded. Every kilobyte here lands in a tracked
    file, so anything unused is pure merge noise for whoever reviews that diff next."""
    lines = [BEGIN]
    for name in sorted(n for n in pinned if n in EMBED):
        with open(os.path.join(FONT_DIR, name), "rb") as handle:
            b64 = base64.b64encode(handle.read()).decode("ascii")
        lines.append(_face(pinned[name], f"data:font/woff2;base64,{b64}"))
    lines.append(END)
    return "\n".join(lines) + "\n"


def _splice_dashboard(css):
    """Kept in its own <style> at the end of <head>, never mixed into the hand-written CSS, so
    the generated blob cannot shift the line numbers of anything a human maintains."""
    with open(DASHBOARD_PATH, encoding="utf-8") as handle:
        page = handle.read()
    block = "<style>\n" + css.strip() + "\n</style>\n"
    if BEGIN in page and END in page:
        start, tail = page.split("<style>\n" + BEGIN, 1)
        _, rest = tail.split(END + "\n</style>\n", 1)
        page = start + block + rest
    else:
        page = page.replace("</head>", block + "</head>", 1)
    with open(DASHBOARD_PATH, "w", encoding="utf-8", newline="") as handle:
        handle.write(page)


def _load_manifest():
    if not os.path.exists(MANIFEST_PATH):
        return {}
    with open(MANIFEST_PATH, encoding="utf-8") as handle:
        return json.load(handle)


def verify():
    manifest = _load_manifest()
    if not manifest:
        raise SystemExit("no manifest — run `fetch` first")
    bad = 0
    for name, meta in sorted((manifest.get("files") or {}).items()):
        path = os.path.join(FONT_DIR, name)
        if not os.path.exists(path):
            print(f"  MISSING  {name}")
            bad += 1
            continue
        with open(path, "rb") as handle:
            digest = hashlib.sha256(handle.read()).hexdigest()
        ok = digest == meta["sha256"]
        print(f"  {'ok      ' if ok else 'MISMATCH'} {name}")
        bad += 0 if ok else 1
    print("\nRESULT:", "FONTS VERIFIED" if not bad else f"{bad} PROBLEM(S)")
    return 0 if not bad else 1


def status():
    manifest = _load_manifest()
    if not manifest:
        print("no local fonts — both surfaces fall back to Georgia and Consolas")
        return 0
    files = manifest.get("files") or {}
    present = sum(1 for name in files if os.path.exists(os.path.join(FONT_DIR, name)))
    print(f"manifest pins {len(files)} faces; {present} present on disk")
    print(f"fonts.css     {'present' if os.path.exists(CSS_PATH) else 'MISSING — re-run fetch'}")
    with open(DASHBOARD_PATH, encoding="utf-8") as handle:
        print("dashboard     " + ("embedded" if BEGIN in handle.read() else "NOT embedded — re-run fetch"))
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("command", choices=["fetch", "verify", "status"])
    args = ap.parse_args()
    try:
        raise SystemExit({"fetch": fetch, "verify": verify, "status": status}[args.command]() or 0)
    except urllib.error.URLError as error:
        raise SystemExit(f"download failed: {error}")


if __name__ == "__main__":
    main()
