"""Prepare distinct, labelled SYNTHETIC folders for a multi-desktop rehearsal.

The generated baseline makes the privacy/utility charts less dominated by noise while a presenter
can still add locally extracted videos to each node folder. Metrics remain engineering-demo results,
not clinical evidence.

  uv run python stage_demo_nodes.py
  uv run python stage_demo_nodes.py --modality action_cdp --per-class 10
  uv run python stage_demo_nodes.py --refresh

``--refresh`` removes only files recorded in this tool's own manifest. It never recursively deletes
the staging root, user-extracted clips, node keys, or unrelated files.
"""
import argparse
import json
import os
import shutil
import tempfile

import modalities as mods

HERE = os.path.dirname(os.path.abspath(__file__))
MANIFEST = ".gba-df-synthetic-stage.json"
NOTICE = "SYNTHETIC-DATA.txt"
NOTICE_TEXT = """SYNTHETIC ENGINEERING-DEMO DATA

Files beginning with synthetic_ were generated by stage_demo_nodes.py. They are not participant
recordings and carry no clinical meaning. Metrics produced from this folder test software and
privacy/aggregation behaviour; they do not establish screening performance in people.

Other files in this node folder may have been added locally and are not managed by the staging tool.
"""


def _inside(root, relative):
    """Resolve one manifest entry and fail closed if a modified manifest escapes its root."""
    if not isinstance(relative, str) or not relative or os.path.isabs(relative):
        raise ValueError("stage manifest contains an invalid generated path")
    root = os.path.realpath(root)
    target = os.path.realpath(os.path.join(root, relative))
    if os.path.commonpath([root, target]) != root:
        raise ValueError("stage manifest contains a path outside its staging root")
    return target


def _read_manifest(root):
    path = os.path.join(root, MANIFEST)
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as handle:
        manifest = json.load(handle)
    if manifest.get("format") != "gba-df-synthetic-stage" or manifest.get("version") != 1:
        raise ValueError("unrecognized synthetic-stage manifest; refusing to refresh")
    if not isinstance(manifest.get("generated_files"), list):
        raise ValueError("synthetic-stage manifest has no generated file list")
    return manifest


def _remove_previous(root, manifest):
    removed = 0
    for relative in manifest["generated_files"]:
        target = _inside(root, relative)
        if os.path.isfile(target):
            os.unlink(target)
            removed += 1
    return removed


def _write_manifest(root, payload):
    fd, temporary = tempfile.mkstemp(prefix=f".{MANIFEST}-", dir=root, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
            handle.write("\n")
        os.replace(temporary, os.path.join(root, MANIFEST))
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def _copy_synthetic_source(source, node_dir):
    generated = []
    for current, _dirs, files in os.walk(source):
        for name in sorted(files):
            relative_parent = os.path.relpath(current, source)
            target_dir = node_dir if relative_parent == "." else os.path.join(node_dir, relative_parent)
            os.makedirs(target_dir, exist_ok=True)
            target = os.path.join(target_dir, f"synthetic_{name}")
            if os.path.exists(target):
                raise FileExistsError(f"refusing to overwrite an unmanaged file: {target}")
            shutil.copy2(os.path.join(current, name), target)
            generated.append(target)
    return generated


def stage_node(root, modality, per_class, seed, index):
    mod = mods.get(modality)
    node_dir = os.path.join(root, f"node_{index}")
    os.makedirs(node_dir, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=f"gba-df-node-{index}-") as source:
        made = mod.synth_folder(source, per_class, seed=seed)
        generated = _copy_synthetic_source(source, node_dir)
    notice = os.path.join(node_dir, NOTICE)
    if os.path.exists(notice):
        raise FileExistsError(f"refusing to overwrite an unmanaged notice: {notice}")
    with open(notice, "w", encoding="utf-8") as handle:
        handle.write(NOTICE_TEXT)
    generated.append(notice)
    X, y, _groups = mod.extract_folder(node_dir)
    labels = {str(label): int((y == label).sum()) for label in sorted(set(y.tolist()))}
    return node_dir, made, generated, X.shape, labels


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--modality", default="action", choices=list(mods.MODALITIES))
    parser.add_argument("--nodes", type=int, default=3)
    parser.add_argument("--per-class", type=int, default=10,
                        help="synthetic recording files per class and node")
    parser.add_argument("--out", default=os.path.join("data", "staged_nodes"),
                        help="staging root (default: ignored runtime data/staged_nodes)")
    parser.add_argument("--seed", type=int, default=100,
                        help="base seed; every node receives a distinct deterministic offset")
    parser.add_argument("--refresh", action="store_true",
                        help="replace only files listed in the prior stage manifest")
    args = parser.parse_args()
    if not 1 <= args.nodes <= 20:
        raise SystemExit("--nodes must be between 1 and 20")
    if not 1 <= args.per_class <= 1000:
        raise SystemExit("--per-class must be between 1 and 1000")

    root = os.path.realpath(args.out if os.path.isabs(args.out) else os.path.join(HERE, args.out))
    os.makedirs(root, exist_ok=True)
    try:
        previous = _read_manifest(root)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        raise SystemExit(str(error))
    visible = [name for name in os.listdir(root) if name != MANIFEST]
    if previous is None and visible:
        raise SystemExit(f"{root} is not an empty managed stage; choose another --out directory")
    if previous is not None and not args.refresh:
        raise SystemExit(f"{root} is already staged; pass --refresh to replace generated files only")
    if previous is not None:
        try:
            removed = _remove_previous(root, previous)
        except (OSError, ValueError) as error:
            raise SystemExit(str(error))
        print(f"Removed {removed} previously generated files; local additions were preserved.")

    generated = []
    print(f"Staging {args.nodes} distinct '{args.modality}' node folders under {root}")
    for index in range(1, args.nodes + 1):
        node_dir, made, files, shape, labels = stage_node(
            root, args.modality, args.per_class, args.seed + index * 17, index)
        generated.extend(os.path.relpath(path, root) for path in files)
        print(f"  node_{index}: {made} synthetic files -> {shape[0]} rows × {shape[1]} features "
              f"{labels}\n           {node_dir}")
    _write_manifest(root, {"format": "gba-df-synthetic-stage", "version": 1,
                           "modality": args.modality, "nodes": args.nodes,
                           "per_class": args.per_class, "base_seed": args.seed,
                           "generated_files": sorted(generated),
                           "warning": "synthetic engineering-demo data; not clinical evidence"})
    print("\nChoose a different node_<n> folder in each desktop client. If you add raw videos, point")
    print("Advanced settings -> extracted NPZ folder at that same node_<n> folder.")
    print("The generated recordings are synthetic. Say so during the demonstration.")


if __name__ == "__main__":
    main()
