"""Stage one local data folder per demo node: a labelled SYNTHETIC baseline cohort that the
live, on-stage video extraction then adds to.

Why this exists. A demo makes two different claims, and they need different amounts of data:
raw data never leaves the machine (a single recording proves it), and federated training tracks
the centralized-DP reference (a handful of rows cannot show it — the DP noise swamps them and
the AUC becomes a coin flip). Giving every node a baseline cohort lets one run carry both.

Each node gets its OWN seed, so the three folders are genuinely different institutions rather
than three copies of the same recordings. Every generated file is named `synthetic_…` and sits
under a `SYNTHETIC-DATA.txt` marker: these are not real participants and must never be
presented as clinical evidence.

  uv run python stage_demo_nodes.py                               # 3 nodes, action, 6/class
  uv run python stage_demo_nodes.py --modality action_cdp --per-class 8
  uv run python stage_demo_nodes.py --force                       # regenerate over an old stage

Point each desktop client at demo_nodes/node_<n> (step 2 "Choose NPZ folder…", and Advanced
settings -> permanent video folder) so extracted clips land in the same place.
"""
import argparse
import os
import shutil

import modalities as mods

HERE = os.path.dirname(os.path.abspath(__file__))
MARKER = "SYNTHETIC-DATA.txt"
NOTE = """This folder holds SYNTHETIC recordings generated by stage_demo_nodes.py.

They are not real participants and carry no clinical meaning. They exist so a demo federation
has enough rows for the privacy/utility comparison to be meaningful; any metric produced from
them is an engineering check, not evidence about people.

Files named synthetic_*.npz are generated. Anything else in here was put here by you (for
example clips extracted from your own video in the desktop client).
"""


def stage(out_dir, modality, per_class, seed):
    mod = mods.get(modality)
    os.makedirs(out_dir, exist_ok=True)
    made = mod.synth_folder(out_dir, per_class, seed=seed)
    renamed = 0
    for root, _dirs, files in os.walk(out_dir):
        for name in files:
            if name.endswith(".npz") and not name.startswith("synthetic_"):
                os.replace(os.path.join(root, name), os.path.join(root, f"synthetic_{name}"))
                renamed += 1
    with open(os.path.join(out_dir, MARKER), "w", encoding="utf-8") as f:
        f.write(NOTE)
    return made, renamed


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--modality", default="action", choices=list(mods.MODALITIES))
    ap.add_argument("--nodes", type=int, default=3)
    ap.add_argument("--per-class", type=int, default=6,
                    help="synthetic clip files per class per node")
    ap.add_argument("--out", default="demo_nodes", help="staging root")
    ap.add_argument("--seed", type=int, default=100, help="base seed; each node offsets from it")
    ap.add_argument("--force", action="store_true", help="delete an existing stage first")
    args = ap.parse_args()

    root = args.out if os.path.isabs(args.out) else os.path.join(HERE, args.out)
    if os.path.exists(root):
        if not args.force:
            raise SystemExit(f"{root} already exists — pass --force to regenerate it "
                             f"(this deletes anything you extracted into it)")
        shutil.rmtree(root)

    mod = mods.get(args.modality)
    print(f"Staging {args.nodes} node folders for '{args.modality}' under {root}")
    for index in range(1, args.nodes + 1):
        node_dir = os.path.join(root, f"node_{index}")
        made, renamed = stage(node_dir, args.modality, args.per_class, args.seed + index * 17)
        X, y, groups = mod.extract_folder(node_dir)
        labels = {}
        for label in y:
            labels[str(label)] = labels.get(str(label), 0) + 1
        print(f"  node_{index}: {made} synthetic files ({renamed} marked) -> "
              f"{X.shape[0]} rows x {X.shape[1]} features, {labels}")
        print(f"           {node_dir}")

    print("\nIn each desktop client:")
    print("  step 2 -> Choose NPZ folder…            -> the node_<n> folder above")
    print("  Advanced settings -> permanent folder   -> the SAME node_<n> folder,")
    print("                                             so extracted video lands beside it")
    print("\nThe generated recordings are synthetic. Say so on stage.")


if __name__ == "__main__":
    main()
